spring:
  application:
    name: user-service

    data:
      mongodb:
        uri: mongodb://localhost:27017/user_service_db
app:
  jwt:
    secret: myverystrongsecretkeyforhs256algorithm12345
    expiration-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8082
