spring:
  application:
    name: inventory-service

  kafka:
    bootstrap-servers:  ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

  data:
    mongodb:
      uri: ${INVENTORY_DB}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8081